<?php

namespace AppBundle\Repository;

/**
 * DevisAutocarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevisAutocarRepository extends \Doctrine\ORM\EntityRepository
{
}
